name: Compile SymCC RT
on: [pull_request, workflow_dispatch]
jobs:
  build_symcc:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        llvm_version: [11, 12, 13, 14, 15]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            llvm-${{ matrix.llvm_version }}-dev \
            libz3-dev \
      - name: Build SymCC with the QSYM backend
        run: |
          mkdir build
          cd build
          cmake -G Ninja  \
            -DCMAKE_BUILD_TYPE=Release \
            -DZ3_TRUST_SYSTEM_VERSION=ON \
            -DSYMCC_RT_BACKEND=qsym \
            -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm_version }}/cmake \
            ..
          ninja
      - name: Build SymCC with the simple backend
        run: |
          mkdir build
          cd build
          cmake -G Ninja\
            -DCMAKE_BUILD_TYPE=Release \
            -DZ3_TRUST_SYSTEM_VERSION=ON \
            -DSYMCC_RT_BACKEND=qsym \
            -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm_version }}/cmake \
            ..
          ninja
  llvm_compatibility_latest_llvm:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        llvm_version: [16, 17]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Add LLVM project deb repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${{ matrix.llvm_version }} main
          repo-name: llvm
          update: false
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            llvm-${{ matrix.llvm_version }}-dev \
            libz3-dev \
      - name: Build SymCC with the QSYM backend
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DZ3_TRUST_SYSTEM_VERSION=ON \
            -DQSYM_BACKEND=ON \
            -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm_version }}/cmake \
            ..
          ninja
          
